export const DEFAULT_EXCLUDE_PATTERNS = `**/CHANGELOG.md
**/changelog.md
**/CHANGELOG.mdx
**/changelog.mdx
**/LICENSE
**/LICENSE.md
**/license.md
**/CODE_OF_CONDUCT.md
**/code_of_conduct.md
**/*.test.*
**/*.spec.*
**/*_test.py
**/*_test.go
**/*.lock
**/package-lock.json
**/yarn.lock
**/pnpm-lock.yaml
**/go.sum
**/*.min.js
**/*.min.css
**/*.map
**/*.d.ts
**/.DS_Store
**/Thumbs.db
**/*.swp
**/*.swo
/.*\\.(ini|cfg|conf|log|pid)$/
**/archive/**
**/archived/**
**/deprecated/**
**/legacy/**
**/old/**
**/outdated/**
**/previous/**
**/superseded/**
docs/old/**
**/test/**
**/tests/**
**/__tests__/**
**/spec/**
**/dist/**
**/build/**
**/out/**
**/target/**
**/.next/**
**/.nuxt/**
**/.vscode/**
**/.idea/**
**/i18n/ar*/**
**/i18n/de*/**
**/i18n/es*/**
**/i18n/fr*/**
**/i18n/hi*/**
**/i18n/it*/**
**/i18n/ja*/**
**/i18n/ko*/**
**/i18n/nl*/**
**/i18n/pl*/**
**/i18n/pt*/**
**/i18n/ru*/**
**/i18n/sv*/**
**/i18n/th*/**
**/i18n/tr*/**
**/i18n/vi*/**
**/i18n/zh*/**
**/zh-cn/**
**/zh-hk/**
**/zh-mo/**
**/zh-sg/**
**/zh-tw/**`
